version: '3.9'

services:
    dbpostgresql:
        image: postgres:15-alpine
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 50M
        volumes:
            - db_postgresql:/var/lib/postgresql/data
        container_name: dbpostgresql
        networks:
            - project-network
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: "Postgres2022!"

    message.broker.rabbitmq:
        build: ./infra/rabbitmq/
        container_name: messagebrokerrabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - project-network

    redis:
        image: redis:6.2-alpine
        container_name: redis
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 50M
        networks:
            - project-network
        ports:
            - '6379:6379'
        volumes: 
            - cache:/data

    accountsapi:
        build:
            context: ./accounts.api
            dockerfile: Dockerfile
        container_name: accounts-api
        ports:
            - "9501:8080"
        networks: 
            - project-network
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - dbpostgresql
            - message.broker.rabbitmq
            - redis

    fileapi:
        build:
            context: ./file.api
            dockerfile: Dockerfile
        container_name: file-api
        ports:
            - "9502:8080"
        networks: 
            - project-network
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        volumes:
            - uploads:/app/Uploads
        depends_on:
            - dbpostgresql
            - message.broker.rabbitmq
            - redis
    projectapi:
        build:
            context: ./project.api
            dockerfile: Dockerfile
        container_name: project-api
        ports:
            - "9503:8080"
        networks: 
            - project-network
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        volumes:
            - uploads:/app/Uploads
        depends_on:
            - dbpostgresql
            - message.broker.rabbitmq
            - redis

    accountsloginweb:
        build:
            context: ./accounts.login.web
            dockerfile: Dockerfile
        container_name: accounts.login.web
        ports:
            - "9001:8080"
        networks: 
            - project-network
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - dbpostgresql
            - message.broker.rabbitmq
            - redis
            - accountsapi

    accountsmanagementweb:
        build:
            context: ./accounts.management.web
            dockerfile: Dockerfile
        container_name: accounts.management.web
        ports:
            - "9002:8080"
        networks: 
            - project-network
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - dbpostgresql
            - message.broker.rabbitmq
            - redis
            - accountsloginweb

volumes:
    cache:
        driver: local
    uploads:
        driver: local
    db_postgresql:
        driver: local
        
networks:
  project-network:
    driver: bridge