CREATE TABLE "Project" (
    "Id" UUID PRIMARY KEY,
    "CreatedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    "DeletedAt" TIMESTAMP WITHOUT TIME ZONE NULL,
    "CompanyId" UUID NOT NULL,
    "Name" VARCHAR(255) NOT NULL,
    "Description" TEXT,
    "UserCreatedId" UUID NOT NULL,
    "Status" INT NOT NULL  
);

CREATE TABLE "Member" (
    "Id" UUID PRIMARY KEY,
    "CreatedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    "DeletedAt" TIMESTAMP WITHOUT TIME ZONE NULL,
    "ProjectId" UUID NOT NULL,
    "UserId" UUID NOT NULL,
    "Status" INT NOT NULL  
);

ALTER TABLE "Member"
ADD CONSTRAINT "FK_Member_Project"
FOREIGN KEY ("ProjectId") REFERENCES "Project"("Id");
