
CREATE TABLE Project (
    Id UUID PRIMARY KEY,
    CreatedAt TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    UpdatedAt TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    Name VARCHAR(255) NOT NULL,
    Description TEXT,
    UserCreatedId UUID NOT NULL
);

CREATE TABLE Member (
    Id UUID PRIMARY KEY,
    CreatedAt TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    UpdatedAt TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    ProjectId UUID NOT NULL,
    UserId UUID NOT NULL,
    Profile INT NOT NULL, -- Enum mapeado como inteiro
    Status INT NOT NULL   -- Enum mapeado como inteiro
);

ALTER TABLE Member
ADD CONSTRAINT FK_Member_Project
FOREIGN KEY (ProjectId) REFERENCES Project(Id);
