location = /accounts {
    return 301 /accounts/;
}

location /accounts/ {
    proxy_pass http://accountsloginweb:8080;

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location = /accounts-management {
    return 301 /accounts-management/;
}

location /accounts-management/ {
    proxy_pass http://accountsmanagementweb:8080;

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location = /project {
    return 301 /project-web/;
}

location /project/ {
    proxy_pass http://projectweb:80;

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
